apiVersion: v1
kind: Service
metadata:
  name: nginx-status
  labels:
    app: nginx-status
spec:
  selector:
    app: nginx-status
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx-exporter
    port: 9113
    protocol: TCP
    targetPort: 9113
