apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-status-service-monitor
  namespace: default
  labels:
    release: kind-prometheus
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: nginx-status
  endpoints:
    - port: nginx-exporter
      path: '/metrics'

